### ISSUE TITLE
Check for un-acknowledged purchases and acknowledge them

### ISSUE THREAD

**Issue by joycetoh8** [chromeos/pwa-play-billing#20]
During the code refactor and reorg, this flow got lost. Every time `refreshPurchases` is called, it's a good idea to check for any purchases where the `acknowledge` field isn't true, then acknowledge those purchase tokens.

**Comment by nohe427** [comment]
@joycetoh8  Closed by #24 ?

**Comment by nohe427** [comment]
Bumping @joycetoh8

**Comment by joycetoh8** [comment]
Yep, closed by #24!
