### ISSUE TITLE
The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console.

### ISSUE THREAD

**Issue by mikecann** [chromeos/pwa-play-billing#39]
Hi, 

Thanks for such a helpful sample and guide, we have used it to successfully manage to make a purchase on ChromeOS using Google Play Billing. 

The problem however is when we come to fetch the purchase from the api (https://github.com/chromeos/pwa-play-billing/blob/main/functions/src/purchases.ts#L81) then we get the following error:

```
Error: The current user has insufficient permissions to perform the requested operation.
```

I am sure I am using the correct keys attached to the service account that is linked in the Google Play Console.

Just to be sure I used this page to test the API: https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptions/get

And I get a different error:

```
{
  "error": {
    "code": 403,
    "message": "The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console.",
    "errors": [
      {
        "message": "The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console.",
        "domain": "androidpublisher",
        "reason": "projectNotLinked"
      }
    ]
  }
}
```

Which is really odd because it is linked.

It seems like there are a great many people that have had the same issue: https://stackoverflow.com/questions/25481207/error-the-project-id-used-to-call-the-google-play-developer-api-has-not-been-l

I have followed the suggestions listed on there (delete and recreate the store item) to no avail.

We are really kind of stuck and not sure what to do, any clues?

**Comment by joycetoh8** [comment]
Hi Mike,

Thanks for checking out the sample and for the question! I know setting up access to the Play Developer API can be confusing so thank you for your patience. 

Based on what you've shared, it sounds like you've gone through the steps [in the Play Developer API section of the README](https://github.com/chromeos/pwa-play-billing#google-play-developer-api) already. Here are some places to double-check.

- Can you confirm the role for your service account is at least "Service account user" (you could also try giving the service account full "Owner" permissions)? 
- In the "API Access" page in your Play Console, click "View access" for the service account you're using. Make sure it has access to the app you want. I think we recommend just giving it "Manage orders and subscriptions" permission, but again you could try giving the full "Admin" permissions.
- Also double-check that the service account credentials are correct in [functions/src/config.ts](https://github.com/chromeos/pwa-play-billing/blob/main/functions/src/config.ts#L21-L23). Make sure the service account email is the same as the one listed under "API Access". For the private key, copy the ENTIRE string as is from the key file (including the `-----BEGIN PRIVATE KEY-----` and `-----END PRIVATE KEY-----\n` parts of the string. Then deploy your backend if you made any changes.

Please let me know if it still doesn't work. Thanks!

**Comment by mikecann** [comment]
Hi @joycetoh8,

Thanks for repying so quickly, we are really at a loss how to proceed so we very much value any help you can offer.

> Can you confirm the role for your service account is at least "Service account user" (you could also try giving the service account full "Owner" permissions)?

![image](https://user-images.githubusercontent.com/215033/135046924-64aa0ee0-5089-4cd4-abd4-321a586d5523.png)

> In the "API Access" page in your Play Console, click "View access" for the service account you're using. Make sure it has access to the app you want. I think we recommend just giving it "Manage orders and subscriptions" permission, but again you could try giving the full "Admin" permissions.

![image (7)](https://user-images.githubusercontent.com/215033/135047060-cece00f7-d81d-4286-adf9-0aa8bfcf83ad.png)

![image (8)](https://user-images.githubusercontent.com/215033/135047093-ac24fc53-6a82-4829-8795-8a000d955856.png)

![image (9)](https://user-images.githubusercontent.com/215033/135047131-e122f65f-6378-4af8-b89e-e4c97d71992b.png)

> Also double-check that the service account credentials are correct in functions/src/config.ts. Make sure the service account email is the same as the one listed under "API Access". For the private key, copy the ENTIRE string as is from the key file (including the -----BEGIN PRIVATE KEY----- and -----END PRIVATE KEY-----\n parts of the string. Then deploy your backend if you made any changes

Yes this is confirmed.

I think to simplify things a bit more. 

This page: https://developers.google.com/android-publisher/api-ref/rest/v3/inappproducts/list?apix_params=%7B%22packageName%22%3A%22io.battletabs.twa%22%7D

Returns this error: 

```
{
  "error": {
    "code": 403,
    "message": "The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console.",
    "status": "PERMISSION_DENIED"
  }
}
```

If I understand it correctly I think this is the source of the problems. If this call works then I think the https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptions/get should work too. 

As you can see from the supplied screenshots above however we are pretty sure we have everything linked correctly.

Any ideas?

**Comment by joycetoh8** [comment]
Thanks for double-checking everything. You're right, everything looks great and the service account looks like its linked correctly. The only thing I can think of is that it can sometimes take 24-48 hours for the service account permissions to sync and API calls to start working. 

If it's any consolation, when using https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.products/get to test the API, I also see the same errors you do. I'm not entirely sure how that works and how it's retrieving credentials and why it would error, cause I'm not seeing those errors in our actual live sample. All to say, I'm not sure it's an accurate indicator of whether you've got your own code set up correctly.

**Comment by mikecann** [comment]
> All to say, I'm not sure it's an accurate indicator of whether you've got your own code set up correctly.

Oh really? Ah okay I have been relying on that as an indicator for if things are working. I wanted to reduce variables such as malformed credentials or something by using that API explorer.

Okay ill go back to manually testing using our own backend and putting fake purchases through.

**Comment by mikecann** [comment]
WTF.. just tried using our backend and it now works!! 

Oh my god! :D 

Wow if it really does take that that long for permissions to sync accross and the API exporer from the docs give you permission errors no matter what that is a MASSIVE gotcha and really should be highlighted in bold magenta font everywhere. We just wasted days and earned some more grey hairs over this :(

Thanks for your assistance with this.
